'use client'
import Button from '../../../../../packages/ui/src/button'
import { useState } from 'react'
import RandomIntegerGame from '@repo/math/RandomIntegerGame'
import getRandomIntegerGameMenu from '@repo/math/RandomIntegerGameMenu'
import { getRandomInteger } from '@repo/math/getRandomInteger'
